title:    Rajarathnam Balakrishnan # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UC Berkeley Grad <br>
  Deep Learning and Machine Learning Enthusiast. 
  <br><br>
  Hello there! I'm Raja!
  <br>
  Thank you for taking the time to know more about my works. 
  <br>
  <br>
  <a href="/pdf/Rajarathnam_Balakrishnan_Resume.pdf" class="image fit">
  Resume | 
  </a>
  <a href='https://www.linkedin.com/in/rajarathnam-balakrishnan-7b447b135' target = '_blank'>
  LinkedIn | 
  </a>
  <a href='https://github.com/rajarathnambalakrishnan' target = '_blank'>
  GitHub Page
  </a>
  <br>
  <a href='mailto: rajarathnam_b@berkeley.edu'>
  rajarathnam_b@berkeley.edu
  </a>
  <br>
  <a href='mailto: rajarathnambalakrishnan@gmail.com'>
  rajarathnambalakrishnan@gmail.com
  </a>
  
theme: jekyll-theme-minimal
google_analytics: G-JYEVT2EE4D