title: Rajarathnam Balakrishnan # your name (or website title) here
#logo: "/images/profile.png?raw=true" # your photo (or logo) here
<img style="float: left;" src="/images/profile.png?raw=true" width="100" height="100"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Enthusiast, Startups passionate 
  <br><br>
  I'm Raja! Thank you for taking the time to know more about me.
  <br>
  I'm from Chennai, India. I have a Bachelors in Mechanical Engineering and just completed my Masters in Industrial Engineering and Operations Research at UC Berkeley.
  <br>
  <a href='https://www.linkedin.com/in/francesco-piccoli'>
  <img src="/images/linkedin.png?raw=true" width="30" height="30">
  </a>
  <a href='https://github.com/Francesco-Piccoli'>
  <img src="/images/github.png?raw=true" width="30" height="30">
  </a>
  <a href=''>
  <img src="/images/instagram.png?raw=true" width="30" height="30">
  </a>
  <a href='https://www.instagram.com/francescopiccoli.fp/?hl=en'>
  <img src="/images/instagram.png?raw=true" width="30" height="30">
  </a>
theme: jekyll-theme-minimal
