title: Rajarathnam Balakrishnan # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Deep Learning and Machine Learning Enthusiast, Passionate in Autonomous Vehicles 
  <br><br>
  Hello there! I'm Raja!
  <br>
  Thank you for taking the time to know more about me. I'm from Chennai, India. 
  I have a Bachelors in Mechanical Engineering and just completed my Masters in 
  Industrial Engineering and Operations Research at UC Berkeley.
  <br>
  </a>
  <a href='https://www.linkedin.com/in/rajarathnam-balakrishnan-7b447b135'>
  <img src="/images/linkedin.png" width="30" height="30">
  </a>
  <br>
  </a>
  <a href='https://github.com/rajarathnambalakrishnan'>
  <img src="/images/github.png" width="30" height="30">
  </a>
  <br>
  <img src="/images/gmail.png" width="30" height="30">
  <a href='mailto: rajarathnam_b@berkeley.edu'>
  email
  </a>
  <br>
  <img src="/images/gmail.png" width="30" height="30">
  <a href='mailto: rajarathnambalakrishnan@gmail.com'>
  email
  </a>
  
theme: jekyll-theme-minimal
