title:    Rajarathnam Balakrishnan # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Deep Learning and Machine Learning Enthusiast, Passionate in Autonomous Vehicles 
  <br><br>
  Hello there! I'm Raja!
  <br>
  Thank you for taking the time to know more about me. 
  I'm a recent UC Berkeley Grad.
  <br>
  <br>
  <a href="/pdf/Rajarathnam Balakrishnan Resume.pdf" download>My Resume </a>
  <br>
  <a href='https://www.linkedin.com/in/rajarathnam-balakrishnan-7b447b135' target = '_blank'>
  LinkedIn Page
  </a>
  <br>
  <a href='https://github.com/rajarathnambalakrishnan' target = '_blank'>
  GitHub Page
  </a>
  <br>
  <a href='mailto: rajarathnam_b@berkeley.edu'>
  rajarathnam_b@berkeley.edu
  </a>
  <br>
  <a href='mailto: rajarathnambalakrishnan@gmail.com'>
  rajarathnambalakrishnan@gmail.com
  </a>
  
theme: jekyll-theme-minimal